name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
      - uses: pnpm/action-setup@v2
        with:
          version: 7.2.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
